-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.casualities
(
    casualities_id integer NOT NULL,
    fatalities integer,
    affected bigint,
    evacuated bigint,
    estimated_total_cost bigint,
    normalized_total_cost bigint,
    location_id integer NOT NULL,
    event_id integer,
    CONSTRAINT casualities_pkey PRIMARY KEY (casualities_id)
);

CREATE TABLE IF NOT EXISTS public.events
(
    event_id integer NOT NULL,
    category character varying(15) COLLATE pg_catalog."default",
    event_group character varying(20) COLLATE pg_catalog."default",
    subgroup character varying(40) COLLATE pg_catalog."default",
    event_type character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT events_pkey PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS public.locations
(
    location_id integer NOT NULL,
    locations character varying(200) COLLATE pg_catalog."default",
    event_start_date date,
    event_end_date date,
    event_id integer NOT NULL,
    CONSTRAINT locations_pkey PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS public.relief_aid
(
    relief_aid_id integer NOT NULL,
    federal_payments bigint,
    provincial_payments bigint,
    provincial_department_payments bigint,
    insurance_payments bigint,
    event_id integer NOT NULL,
    CONSTRAINT relief_aid_pkey PRIMARY KEY (relief_aid_id)
);

ALTER TABLE IF EXISTS public.casualities
    ADD CONSTRAINT location_id FOREIGN KEY (location_id)
    REFERENCES public.locations (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.casualities
    ADD CONSTRAINT event_id FOREIGN KEY (event_id)
    REFERENCES public.events (event_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.locations
    ADD CONSTRAINT locations_event_id_fkey FOREIGN KEY (event_id)
    REFERENCES public.events (event_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.relief_aid
    ADD CONSTRAINT relief_aid_event_id_fkey FOREIGN KEY (event_id)
    REFERENCES public.events (event_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;